name: Fast Windows CI

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

env:
  PROJECT_NAME: "MasmLint"
  VERBOSE: 1
  nproc: 4

jobs:
  Test:
    runs-on: [self-hosted, windows]
    strategy:
      fail-fast: false

      matrix:
        include:
          - compiler: clang
            generator: Ninja Multi-Config
            build_type: Release

    steps:
      - name: Print config
        run: |
          echo "os = Windows"
          echo "compiler = ${{matrix.compiler}}"
          echo "generator = ${{matrix.generator}}"
          echo "build_type = ${{matrix.build_type}}"

      # - name: Setup environment
      #   run: |
      #     choco install ninja
      #     choco install llvm
      #     choco install opencppcoverage

      - uses: actions/checkout@v4
        with:
          set-safe-directory: "MasmLint"

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -G "${{matrix.generator}}" --preset ci-windows-${{matrix.compiler}}-${{matrix.build_type}}

      - name: Build
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build ./build --config ${{matrix.build_type}}
